<a href="https://colab.research.google.com/github/Atul210704/atulsharma/blob/main/day8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import time as t
print(t.time)

<built-in function time>


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[2])
print(arr[4])
print(arr[0:4]) #slicing
print(arr[-1])
print(arr[:])
print(arr[0:3:2]) # start from 0 to 3 & jump1
print(arr[::2]) # jump by one
print(arr[::-1]) # reverse
print(arr[3:5])

3
5
[1 2 3 4]
5
[1 2 3 4 5]
[1 3]
[1 3 5]
[5 4 3 2 1]
[4 5]


In [ ]:
# 2d
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[0:2]) # row
print(arr[:,0]) # all rows | cols 0
print(arr[0,0]) # row -> 1 | cols 1
print(arr[2:2])
print(arr[0:2])

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 4]
1
[]
[[1 2 3]
 [4 5 6]]


In [ ]:
# for loop on numpy
# 1d
import numpy as np
arr = np.array([10,20,30,40])
print(arr)
for i in arr:
  print(i)

[10 20 30 40]
10
20
30
40


In [ ]:
import numpy as np

arr = np.array([[2453,75,183975],[5795,99,573705],[4100,36,147600],
                [7526,86,647236],[9528,45,428760],[10788,17,183396]])

print(arr[0,0], arr[0,1])
print()
print(arr[0,2],arr[1,1])
print()
print(arr[2,0],arr[2,0],arr[2,1],arr[3,2])
print()
print(arr[4,1],arr[5,1])
print()
print(arr[4,2],arr[5,2])


2453 75

183975 99

4100 4100 36 647236

45 17

428760 183396


In [ ]:
# 3d
import numpy as np
arr = np.array([
    [[1,2],
     [3,4]
    ],
    [[5,6],
     [7,8]
    ]
    ])
# print(arr.ndim) # 3d
# print("=>",arr[0]) # block
# print("=>>",arr[0,0]) # block -> row
# print("=>>>",arr[0,0,0]) # block -> row -> cols
#
print(arr[:,0]) # all block -> row -> 0
print(arr[:,:,0]) # all block -> all rows -> cols 0


[[1 2]
 [5 6]]
[[1 3]
 [5 7]]


In [ ]:
# fliter
import numpy as np
arr = np.array([10,20,3,4,90,200])
arr_f = arr[arr > 20]
print(arr_f)


[ 90 200]


In [ ]:
# filter
import numpy as np
arr = np.array([10,20,30,6,3,2])
arr_f = arr[arr !=6]
print(arr_f)

[10 20 30  3  2]


In [ ]:
import numpy as np
arr = np.array([5,6,7,8,11,24,16,19,24])
arr_f = arr[(arr>10) & (arr<20)]
print(arr_f)

[11 16 19]


In [ ]:
# fancy indexing
import numpy as np
arr = np.array([10,20,3,4,90,100])
print(arr)
arr_f = arr[[0,2]] # 0 index value,2 index value
print(arr_f)

[ 10  20   3   4  90 100]
[10  3]


In [ ]:
# where
import numpy as np
arr = np.array([10,20,3,4,90,100])
print(arr)
arr_w= np.where(arr>9,"true","false")
print(arr_w)

[ 10  20   3   4  90 100]
['true' 'true' 'false' 'false' 'true' 'true']


In [ ]:
import numpy as np
arr = np.array([10,20,11,12,13,14,18,88,44,52,90,78,99,25,500])
arr_f = np.where((arr > 10) & (arr < 20) ,arr*2 , arr+2)
print(arr_f)

[ 12  22  22  24  26  28  36  90  46  54  92  80 101  27 502]


In [ ]:
import numpy as np
arr1 = np.array([10,20,30])
arr2 =np.array([1,2,3])


# concatenate
arr_arr2 = np.concatenate((arr1,arr2))
print(arr_arr2)

# concatenate using 2d axis
arr1 = np.array([[10,20,30] ,[40,50,60]])
arr2 = np.array([[1,2,3] ,[4,5,6]])
arr1_arr2 = np.concatenate((arr1,arr2),axis = 0)
print(arr1_arr2)

[10 20 30  1  2  3]
[[10 20 30]
 [40 50 60]
 [ 1  2  3]
 [ 4  5  6]]


In [ ]:
# vstack -> verically join | row wise
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.vstack((arr1,arr2))
print(result)

[[1 2 3]
 [4 5 6]]


In [ ]:
# hstack -> horizontally join | column wise
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
result = np.hstack((arr1,arr2))
print(result)

[10 20 30 40 50 60]


In [ ]:
import numpy as np
arr = np.array([2,4,6,8,10])
print(np.sum(arr))


30


In [ ]:
import numpy as np
arr = np.array([2,4,6,8,10])
print(np.median(arr))

6.0


In [ ]:
import numpy as np
arr = np.array([2,4,6,8,10])
print(np.min(arr))

2


In [ ]:
import numpy as np
arr = np.array([2,4,6,8,10])
print(np.max(arr))

10


In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/Atul210704/atulsharma/main/file.csv"
df = pd.read_csv(url)

print(df)

       name gender
0    nikhil   male
1       raj   male
2  devendra   male
3     hello   male


In [ ]:
# github excel
import pandas as pd
url = "https://raw.githubusercontent.com/Atul210704/atulsharma/main/file.xlsx"
df = pd.read_excel(url)
print(df)

       name gender
0    nikhil   male
1       raj   male
2  devendra   male
3     hello   male


In [ ]:
# github json
import pandas as pd
url = "https://raw.githubusercontent.com/Atul210704/atulsharma/main/data.json"
df = pd.read_json(url)
print(df)

       name  age
0    nikhil   10
1  devendra   20
2       raj   30
3     hello   40


In [4]:
# operations on columns
import pandas as pd
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
df = pd.DataFrame(data)

# select cols
print(df['Emp_ID'])

# select col store in variable
abc = df['Emp_ID']
print(abc)


0    101
1    102
2    103
3    104
4    105
5    106
Name: Emp_ID, dtype: int64
0    101
1    102
2    103
3    104
4    105
5    106
Name: Emp_ID, dtype: int64
