<a href="https://colab.research.google.com/github/Atul210704/atulsharma/blob/main/day8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import time as t
print(t.time)

<built-in function time>


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[2])
print(arr[4])
print(arr[0:4]) #slicing
print(arr[-1])
print(arr[:])
print(arr[0:3:2]) # start from 0 to 3 & jump1
print(arr[::2]) # jump by one
print(arr[::-1]) # reverse
print(arr[3:5])

3
5
[1 2 3 4]
5
[1 2 3 4 5]
[1 3]
[1 3 5]
[5 4 3 2 1]
[4 5]


In [ ]:
# 2d
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[0:2]) # row
print(arr[:,0]) # all rows | cols 0
print(arr[0,0]) # row -> 1 | cols 1
print(arr[2:2])
print(arr[0:2])

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 4]
1
[]
[[1 2 3]
 [4 5 6]]


In [ ]:
# for loop on numpy
# 1d
import numpy as np
arr = np.array([10,20,30,40])
print(arr)
for i in arr:
  print(i)

[10 20 30 40]
10
20
30
40


In [ ]:
import numpy as np

arr = np.array([[2453,75,183975],[5795,99,573705],[4100,36,147600],
                [7526,86,647236],[9528,45,428760],[10788,17,183396]])

print(arr[0,0], arr[0,1])
print()
print(arr[0,2],arr[1,1])
print()
print(arr[2,0],arr[2,0],arr[2,1],arr[3,2])
print()
print(arr[4,1],arr[5,1])
print()
print(arr[4,2],arr[5,2])


2453 75

183975 99

4100 4100 36 647236

45 17

428760 183396


In [ ]:
# 3d
import numpy as np
arr = np.array([
    [[1,2],
     [3,4]
    ],
    [[5,6],
     [7,8]
    ]
    ])
# print(arr.ndim) # 3d
# print("=>",arr[0]) # block
# print("=>>",arr[0,0]) # block -> row
# print("=>>>",arr[0,0,0]) # block -> row -> cols
#
print(arr[:,0]) # all block -> row -> 0
print(arr[:,:,0]) # all block -> all rows -> cols 0


[[1 2]
 [5 6]]
[[1 3]
 [5 7]]


In [ ]:
# fliter
import numpy as np
arr = np.array([10,20,3,4,90,200])
arr_f = arr[arr > 20]
print(arr_f)


[ 90 200]


In [ ]:
# filter
import numpy as np
arr = np.array([10,20,30,6,3,2])
arr_f = arr[arr !=6]
print(arr_f)

[10 20 30  3  2]


In [ ]:
import numpy as np
arr = np.array([5,6,7,8,11,24,16,19,24])
arr_f = arr[(arr>10) & (arr<20)]
print(arr_f)

[11 16 19]


In [ ]:
# fancy indexing
import numpy as np
arr = np.array([10,20,3,4,90,100])
print(arr)
arr_f = arr[[0,2]] # 0 index value,2 index value
print(arr_f)

[ 10  20   3   4  90 100]
[10  3]


In [ ]:
# where
import numpy as np
arr = np.array([10,20,3,4,90,100])
print(arr)
arr_w= np.where(arr>9,"true","false")
print(arr_w)

[ 10  20   3   4  90 100]
['true' 'true' 'false' 'false' 'true' 'true']


In [ ]:
import numpy as np
arr = np.array([10,20,11,12,13,14,18,88,44,52,90,78,99,25,500])
arr_f = np.where((arr > 10) & (arr < 20) ,arr*2 , arr+2)
print(arr_f)

[ 12  22  22  24  26  28  36  90  46  54  92  80 101  27 502]


In [ ]:
import numpy as np
arr1 = np.array([10,20,30])
arr2 =np.array([1,2,3])


# concatenate
arr_arr2 = np.concatenate((arr1,arr2))
print(arr_arr2)

# concatenate using 2d axis
arr1 = np.array([[10,20,30] ,[40,50,60]])
arr2 = np.array([[1,2,3] ,[4,5,6]])
arr1_arr2 = np.concatenate((arr1,arr2),axis = 0)
print(arr1_arr2)

[10 20 30  1  2  3]
[[10 20 30]
 [40 50 60]
 [ 1  2  3]
 [ 4  5  6]]


In [ ]:
# vstack -> verically join | row wise
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.vstack((arr1,arr2))
print(result)

[[1 2 3]
 [4 5 6]]


In [ ]:
# hstack -> horizontally join | column wise
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
result = np.hstack((arr1,arr2))
print(result)

[10 20 30 40 50 60]


In [ ]:
import numpy as np
arr = np.array([2,4,6,8,10])
print(np.sum(arr))


30


In [ ]:
import numpy as np
arr = np.array([2,4,6,8,10])
print(np.median(arr))

6.0


In [ ]:
import numpy as np
arr = np.array([2,4,6,8,10])
print(np.min(arr))

2


In [ ]:
import numpy as np
arr = np.array([2,4,6,8,10])
print(np.max(arr))

10


In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/Atul210704/atulsharma/main/file.csv"
df = pd.read_csv(url)

print(df)

       name gender
0    nikhil   male
1       raj   male
2  devendra   male
3     hello   male


In [ ]:
# github excel
import pandas as pd
url = "https://raw.githubusercontent.com/Atul210704/atulsharma/main/file.xlsx"
df = pd.read_excel(url)
print(df)

       name gender
0    nikhil   male
1       raj   male
2  devendra   male
3     hello   male


In [ ]:
# github json
import pandas as pd
url = "https://raw.githubusercontent.com/Atul210704/atulsharma/main/data.json"
df = pd.read_json(url)
print(df)

       name  age
0    nikhil   10
1  devendra   20
2       raj   30
3     hello   40


In [7]:
# operations on columns
import pandas as pd
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
df = pd.DataFrame(data)

# select cols
print(df['Emp_ID'])

# select col store in variable
abc = df['Emp_ID']
print(abc)

#cols value change
#df['Emp_ID'] = [1,2,3,4,5,6]
#print(df['Emp_ID'])

#cols value change
df['Emp_ID'] = df['Emp_ID'] - 100
print (df['Emp_ID'])

#add new col
df['Amount'] = df['Salary']
print(df)

0    101
1    102
2    103
3    104
4    105
5    106
Name: Emp_ID, dtype: int64
0    101
1    102
2    103
3    104
4    105
5    106
Name: Emp_ID, dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
Name: Emp_ID, dtype: int64
   Emp_ID  Name Department  Salary  Experience  Amount
0       1  Amit         IT   50000           2   50000
1       2  Riya         HR   45000           3   45000
2       3   Raj    Finance   60000           5   60000
3       4  Sara         IT   55000           4   55000
4       5  John      Sales   48000           1   48000
5       6  Neha         HR   52000           3   52000


In [8]:
# operations on columns
import pandas as pd
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
df = pd.DataFrame(data)

# drop cols
df.drop('Emp_ID',axis=1)
print(df)

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3


In [11]:
# operations on columns
import pandas as pd
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
df = pd.DataFrame(data)
print(df)

# 1-> index of row , second -> cols name
print(df.loc[1,"Name"])

#iloc row index -> 0 and cols index -> 0
print(df.iloc[1,1])


   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
Riya
Riya


In [15]:
# operations on columns
import pandas as pd
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
df = pd.DataFrame(data)

# get rows
print(df.loc[[0,1,2]])

# get rows using iloc
print(df.iloc[[1,2,3]])

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
   Emp_ID  Name Department  Salary  Experience
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4


In [18]:
# operations on columns
import pandas as pd
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
df = pd.DataFrame(data)
print(df)

# multi rows & cols
print(df.iloc[[0,1] , [0,1]])

# slicing
print(df.iloc[0:3])

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
   Emp_ID  Name
0     101  Amit
1     102  Riya
   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5


In [19]:
# filter
import pandas as pd
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
df = pd.DataFrame(data)
print(df)

# filter one greater
print(df[df['Emp_ID'] > 104])

# 106
print(df[df['Emp_ID'] == 106])

# 30000 to 50000
# print(df[(condition one) & (condition 2)])
print(df[(df['Salary']> 30000) & (df['Salary'] < 50000)])

   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
   Emp_ID  Name Department  Salary  Experience
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
   Emp_ID  Name Department  Salary  Experience
5     106  Neha         HR   52000           3
   Emp_ID  Name Department  Salary  Experience
1     102  Riya         HR   45000           3
4     105  John      Sales   48000           1


In [24]:
# sorting
# filter
import pandas as pd
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Amit", "Riya", "Raj", "Sara", "John", "Neha"],
    "Department": ["IT", "HR", "Finance", "IT", "Sales", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000, 52000],
    "Experience": [2, 3, 5, 4, 1, 3]
}
df = pd.DataFrame(data)
print(df)

#sorting ascending
print(df.sort_values("Salary",ascending=False))

# two cols
print(df.sort_values(["Salary","Experience"]))


   Emp_ID  Name Department  Salary  Experience
0     101  Amit         IT   50000           2
1     102  Riya         HR   45000           3
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
4     105  John      Sales   48000           1
5     106  Neha         HR   52000           3
   Emp_ID  Name Department  Salary  Experience
2     103   Raj    Finance   60000           5
3     104  Sara         IT   55000           4
5     106  Neha         HR   52000           3
0     101  Amit         IT   50000           2
4     105  John      Sales   48000           1
1     102  Riya         HR   45000           3
   Emp_ID  Name Department  Salary  Experience
1     102  Riya         HR   45000           3
4     105  John      Sales   48000           1
0     101  Amit         IT   50000           2
5     106  Neha         HR   52000           3
3     104  Sara         IT   55000           4
2     103   Raj    Finance   60000           5


In [29]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)
print(df)

print (df)
print (df.head (3))
print (df.tail(3))
print (df. shape)
print (df . rename(columns={'Gender' :'gender"}, inplace=True))
print (df.info())
print (df)
print (df.describe())

print (df[ 'Name'])

# select col store in variable
abc = df[ 'Name']
print (abc)

#cols value change
df[ 'Name'] = [1,2,3,4,5,6,7,8, 9,10, 11, 12,13, 14]
print (df[ 'Name'])

#cols value change
df['Physics"] = df['Physics" ] -100
print (df['Physics' ])

# add new cols
df['Physics'] = df['English' ]
print (df)
print (df. sort_values( "Physics", ascending=False))
print(df. sort_values("English", ascending=True) )
print (df. sort_values(by=["Physics", "English"]))

SyntaxError: unterminated string literal (detected at line 10) (2701227874.py, line 10)

In [32]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd. read_json(url)
print (df)

print (df[ 'gender' ])
print(df[[ "name", "physics"]])
df['physics']= df['physics'] + 10
print (df['physics'])

df .drop("gender", axis=1, inplace=True)
print (df)

print(df.loc[1, "name"])
print (df.iloc[1,1])

print(df.loc[[0,1,2,3]])
print(df.iloc[[1,2,3]])
print(df.iloc[[0,1],[0,1]])

print(df[df[ 'physics' ] > 90])
print(df[df[' name'] == 'raj' ])
print(df.sort_values("physics", ascending=False))

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90
0       Male
1       Male
2       Male
3       Male
4     Female
5     Female
6       Male
7     Female
8       Male
9     Female
10    Female
11      Male
12      Male
13    Female
Name: gender, dtype: object
       name  physics
0      arun       88
1    rajesh       96
2   moorthy       89
3      raja       30
4      ush

KeyError: ' name'